#  --------------------------------------------------------------------------------
version: '3.8'
services:
  mysql:
    networks:
      - bookstore
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  server:
    networks:
        - bookstore
    build: ./
    container_name: go
    working_dir: /SE_MIM22_WEBSHOP_MONO
    ports:
      - "8080:8080"

networks:
  bookstore: null

#    --------------------------------------------------------------------------------

#version: "3.8"
#
#services:
#  web:
#    container_name: BookStoreService
#    build: ./
#    ports:
#      - "8080:8080"
#    environment:
#      DD_DB_HOST: db
#    command: /server
#    depends_on:
#      - db
#
#  db:
#    container_name: BookStoreDatabase
#    image: mysql/mysql-server:5.7
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: books
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
