#  --------------------------------------------------------------------------------
version: '3.8'
services:
  mysql:
    networks:
      - bookstore
    extra_hosts:
      - "mysql:172.0.0.1"
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  server:
    networks:
        - bookstore
    build: ./
    container_name: go
    working_dir: /SE_MIM22_WEBSHOP_MONO
    ports:
      - "8080:8080"

networks:
  bookstore:
    name: "bookstore"
